contact_links:
  - name: 🤔 I have a question
    url: https://github.com/ECLteam/PyTauriX/discussions/categories/q-a
    about: If you have any question that's not clearly a bug, please open a discussion first.
  - name: 💬 Discord Chat
    url: https://discord.gg/TaXhVp7Shw
    about: Engage with PyTauri's users and developers on Discord!
